// Comprehensive configuration for all Indian states and union territories
// with cities, districts, languages, flags, and RSS feed mappings

export interface DistrictConfig {
  name: string;
  headquarters?: string;
  population?: number;
  area?: number; // in sq km
}

export interface StateConfig {
  id: string;
  name: string;
  code: string;
  type: 'state' | 'ut';
  languages: string[];
  capital: string;
  color: string;
  flagUrl?: string; // State flag image
  flagEmoji?: string; // Representative emoji
  region: 'north' | 'south' | 'east' | 'west' | 'central' | 'northeast';
  cities: string[];
  districts: DistrictConfig[];
  rssKeywords?: string[]; // Keywords to match RSS feeds
}

// Language configuration with native scripts
export const LANGUAGE_CONFIG: Record<string, { 
  name: string; 
  native: string; 
  color: string;
  textColor: string;
}> = {
  or: { name: "Odia", native: "ଓଡ଼ିଆ", color: "bg-cyan-500", textColor: "text-cyan-600" },
  hi: { name: "Hindi", native: "हिंदी", color: "bg-orange-500", textColor: "text-orange-600" },
  bn: { name: "Bengali", native: "বাংলা", color: "bg-yellow-500", textColor: "text-yellow-600" },
  ta: { name: "Tamil", native: "தமிழ்", color: "bg-green-500", textColor: "text-green-600" },
  te: { name: "Telugu", native: "తెలుగు", color: "bg-purple-500", textColor: "text-purple-600" },
  mr: { name: "Marathi", native: "मराठी", color: "bg-pink-500", textColor: "text-pink-600" },
  gu: { name: "Gujarati", native: "ગુજરાતી", color: "bg-indigo-500", textColor: "text-indigo-600" },
  kn: { name: "Kannada", native: "ಕನ್ನಡ", color: "bg-red-500", textColor: "text-red-600" },
  ml: { name: "Malayalam", native: "മലയാളം", color: "bg-teal-500", textColor: "text-teal-600" },
  pa: { name: "Punjabi", native: "ਪੰਜਾਬੀ", color: "bg-amber-500", textColor: "text-amber-600" },
  as: { name: "Assamese", native: "অসমীয়া", color: "bg-emerald-500", textColor: "text-emerald-600" },
  ur: { name: "Urdu", native: "اردو", color: "bg-rose-500", textColor: "text-rose-600" },
  ne: { name: "Nepali", native: "नेपाली", color: "bg-lime-500", textColor: "text-lime-600" },
  kok: { name: "Konkani", native: "कोंकणी", color: "bg-fuchsia-500", textColor: "text-fuchsia-600" },
  mni: { name: "Manipuri", native: "মৈতৈলোন্", color: "bg-violet-500", textColor: "text-violet-600" },
  kha: { name: "Khasi", native: "Ka Ktien Khasi", color: "bg-sky-500", textColor: "text-sky-600" },
  miz: { name: "Mizo", native: "Mizo ṭawng", color: "bg-slate-500", textColor: "text-slate-600" },
  bod: { name: "Tibetan", native: "བོད་སྐད", color: "bg-stone-500", textColor: "text-stone-600" },
  en: { name: "English", native: "English", color: "bg-blue-500", textColor: "text-blue-600" },
};

// State flags - using representative colors/symbols
export const STATE_FLAGS: Record<string, { emoji: string; colors: string[] }> = {
  "odisha": { emoji: "🏛️", colors: ["#FF6600", "#FFFFFF"] },
  "maharashtra": { emoji: "🦁", colors: ["#FF9933", "#138808", "#FFFFFF"] },
  "karnataka": { emoji: "🐘", colors: ["#FFC107", "#D32F2F"] },
  "tamil-nadu": { emoji: "🏯", colors: ["#000000", "#D32F2F", "#FFFFFF"] },
  "kerala": { emoji: "🌴", colors: ["#006B3C", "#FFC107"] },
  "west-bengal": { emoji: "🎭", colors: ["#003366", "#FFFFFF"] },
  "gujarat": { emoji: "🦁", colors: ["#FF9933", "#FFFFFF", "#138808"] },
  "rajasthan": { emoji: "🐫", colors: ["#FFD700", "#FF6600"] },
  "punjab": { emoji: "🌾", colors: ["#FF9933", "#000080"] },
  "bihar": { emoji: "🏛️", colors: ["#FF9933", "#138808"] },
  "uttar-pradesh": { emoji: "🕌", colors: ["#1E88E5", "#FFFFFF"] },
  "madhya-pradesh": { emoji: "🐅", colors: ["#FFFFFF", "#FF6600"] },
  "andhra-pradesh": { emoji: "🏯", colors: ["#0066CC", "#FFFFFF", "#FFCC00"] },
  "telangana": { emoji: "🏰", colors: ["#FFC107", "#FF5722", "#4CAF50"] },
  "assam": { emoji: "🦏", colors: ["#FF0000", "#FFFFFF", "#1B5E20"] },
  "jharkhand": { emoji: "⛏️", colors: ["#138808", "#FFFFFF"] },
  "chhattisgarh": { emoji: "🌾", colors: ["#138808", "#FFFFFF", "#FF9933"] },
  "haryana": { emoji: "🌾", colors: ["#1E88E5", "#FFFFFF"] },
  "himachal-pradesh": { emoji: "🏔️", colors: ["#FFFFFF", "#0066CC", "#138808"] },
  "uttarakhand": { emoji: "🏔️", colors: ["#138808", "#FFFFFF"] },
  "goa": { emoji: "🏖️", colors: ["#FFFFFF", "#FF6600", "#138808"] },
  "sikkim": { emoji: "🏔️", colors: ["#FF0000", "#FFFFFF"] },
  "tripura": { emoji: "🎭", colors: ["#138808", "#FF9933"] },
  "meghalaya": { emoji: "☁️", colors: ["#FFD700", "#138808"] },
  "manipur": { emoji: "🌺", colors: ["#1E88E5", "#FFFFFF"] },
  "mizoram": { emoji: "🌸", colors: ["#E91E63", "#FFFFFF", "#1E88E5"] },
  "nagaland": { emoji: "🦅", colors: ["#1E88E5", "#FF5722", "#138808"] },
  "arunachal-pradesh": { emoji: "🌄", colors: ["#1E88E5", "#FFFFFF", "#138808"] },
  "delhi": { emoji: "🏛️", colors: ["#FF9933", "#FFFFFF", "#138808"] },
  "jammu-kashmir": { emoji: "🏔️", colors: ["#FF0000", "#FFFFFF"] },
  "ladakh": { emoji: "🏔️", colors: ["#1E88E5", "#FFD700"] },
  "chandigarh": { emoji: "🏛️", colors: ["#FF9933", "#000000"] },
  "puducherry": { emoji: "🏖️", colors: ["#FFCC00", "#FF6600"] },
  "andaman-nicobar": { emoji: "🏝️", colors: ["#0066CC", "#FFFFFF", "#138808"] },
  "lakshadweep": { emoji: "🏝️", colors: ["#0066CC", "#FFFFFF"] },
  "dadra-nagar-haveli-daman-diu": { emoji: "🌊", colors: ["#138808", "#FFFFFF"] },
};

// Complete configuration for all 28 states
export const INDIAN_STATES_CONFIG: StateConfig[] = [
  {
    id: "odisha",
    name: "Odisha",
    code: "OD",
    type: "state",
    languages: ["or", "en"],
    capital: "Bhubaneswar",
    color: "bg-cyan-500",
    flagEmoji: "🏛️",
    region: "east",
    cities: ["Bhubaneswar", "Cuttack", "Rourkela", "Puri", "Berhampur", "Sambalpur", "Balasore", "Jharsuguda", "Baripada", "Jeypore"],
    districts: [
      { name: "Khordha", headquarters: "Bhubaneswar" },
      { name: "Cuttack", headquarters: "Cuttack" },
      { name: "Sundargarh", headquarters: "Sundargarh" },
      { name: "Ganjam", headquarters: "Chatrapur" },
      { name: "Puri", headquarters: "Puri" },
      { name: "Mayurbhanj", headquarters: "Baripada" },
      { name: "Balasore", headquarters: "Balasore" },
      { name: "Sambalpur", headquarters: "Sambalpur" },
      { name: "Jajpur", headquarters: "Jajpur" },
      { name: "Kendrapara", headquarters: "Kendrapara" },
      { name: "Jagatsinghpur", headquarters: "Jagatsinghpur" },
      { name: "Angul", headquarters: "Angul" },
      { name: "Dhenkanal", headquarters: "Dhenkanal" },
      { name: "Nayagarh", headquarters: "Nayagarh" },
      { name: "Boudh", headquarters: "Boudh" },
      { name: "Kalahandi", headquarters: "Bhawanipatna" },
      { name: "Koraput", headquarters: "Koraput" },
      { name: "Nabarangpur", headquarters: "Nabarangpur" },
      { name: "Rayagada", headquarters: "Rayagada" },
      { name: "Malkangiri", headquarters: "Malkangiri" },
      { name: "Kandhamal", headquarters: "Phulbani" },
      { name: "Bolangir", headquarters: "Bolangir" },
      { name: "Subarnapur", headquarters: "Sonepur" },
      { name: "Bargarh", headquarters: "Bargarh" },
      { name: "Nuapada", headquarters: "Nuapada" },
      { name: "Jharsuguda", headquarters: "Jharsuguda" },
      { name: "Deogarh", headquarters: "Deogarh" },
      { name: "Keonjhar", headquarters: "Keonjhar" },
      { name: "Bhadrak", headquarters: "Bhadrak" },
      { name: "Gajapati", headquarters: "Paralakhemundi" },
    ],
    rssKeywords: ["odisha", "odia", "bhubaneswar", "cuttack", "puri", "ରାଜ୍ୟ"],
  },
  {
    id: "west-bengal",
    name: "West Bengal",
    code: "WB",
    type: "state",
    languages: ["bn", "en", "hi"],
    capital: "Kolkata",
    color: "bg-yellow-500",
    flagEmoji: "🎭",
    region: "east",
    cities: ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Kharagpur", "Malda", "Darjeeling", "Haldia", "Baharampur"],
    districts: [
      { name: "Kolkata", headquarters: "Kolkata" },
      { name: "North 24 Parganas", headquarters: "Barasat" },
      { name: "South 24 Parganas", headquarters: "Alipore" },
      { name: "Howrah", headquarters: "Howrah" },
      { name: "Hooghly", headquarters: "Chinsurah" },
      { name: "Nadia", headquarters: "Krishnanagar" },
      { name: "Murshidabad", headquarters: "Berhampore" },
      { name: "Malda", headquarters: "Malda" },
      { name: "Darjeeling", headquarters: "Darjeeling" },
      { name: "Jalpaiguri", headquarters: "Jalpaiguri" },
      { name: "Cooch Behar", headquarters: "Cooch Behar" },
      { name: "Alipurduar", headquarters: "Alipurduar" },
      { name: "Kalimpong", headquarters: "Kalimpong" },
      { name: "Uttar Dinajpur", headquarters: "Raiganj" },
      { name: "Dakshin Dinajpur", headquarters: "Balurghat" },
      { name: "Birbhum", headquarters: "Suri" },
      { name: "Barddhaman", headquarters: "Barddhaman" },
      { name: "Paschim Bardhaman", headquarters: "Asansol" },
      { name: "Purba Bardhaman", headquarters: "Barddhaman" },
      { name: "Bankura", headquarters: "Bankura" },
      { name: "Purulia", headquarters: "Purulia" },
      { name: "Paschim Medinipur", headquarters: "Medinipur" },
      { name: "Purba Medinipur", headquarters: "Tamluk" },
      { name: "Jhargram", headquarters: "Jhargram" },
    ],
    rssKeywords: ["bengal", "kolkata", "bengali", "বাংলা"],
  },
  {
    id: "bihar",
    name: "Bihar",
    code: "BR",
    type: "state",
    languages: ["hi", "en"],
    capital: "Patna",
    color: "bg-yellow-400",
    flagEmoji: "🏛️",
    region: "east",
    cities: ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga", "Purnia", "Bihar Sharif", "Arrah", "Begusarai", "Katihar"],
    districts: [
      { name: "Patna", headquarters: "Patna" },
      { name: "Gaya", headquarters: "Gaya" },
      { name: "Muzaffarpur", headquarters: "Muzaffarpur" },
      { name: "Bhagalpur", headquarters: "Bhagalpur" },
      { name: "Nalanda", headquarters: "Bihar Sharif" },
      { name: "Vaishali", headquarters: "Hajipur" },
      { name: "Saran", headquarters: "Chapra" },
      { name: "Purnia", headquarters: "Purnia" },
      { name: "Darbhanga", headquarters: "Darbhanga" },
      { name: "Begusarai", headquarters: "Begusarai" },
      { name: "Samastipur", headquarters: "Samastipur" },
      { name: "Madhubani", headquarters: "Madhubani" },
      { name: "Sitamarhi", headquarters: "Sitamarhi" },
      { name: "Bhojpur", headquarters: "Arrah" },
      { name: "Rohtas", headquarters: "Sasaram" },
      { name: "Kaimur", headquarters: "Bhabua" },
      { name: "Buxar", headquarters: "Buxar" },
      { name: "Jehanabad", headquarters: "Jehanabad" },
      { name: "Arwal", headquarters: "Arwal" },
      { name: "Aurangabad", headquarters: "Aurangabad" },
      { name: "Nawada", headquarters: "Nawada" },
      { name: "Jamui", headquarters: "Jamui" },
      { name: "Lakhisarai", headquarters: "Lakhisarai" },
      { name: "Sheikhpura", headquarters: "Sheikhpura" },
      { name: "Munger", headquarters: "Munger" },
      { name: "Khagaria", headquarters: "Khagaria" },
      { name: "Supaul", headquarters: "Supaul" },
      { name: "Saharsa", headquarters: "Saharsa" },
      { name: "Madhepura", headquarters: "Madhepura" },
      { name: "Araria", headquarters: "Araria" },
      { name: "Kishanganj", headquarters: "Kishanganj" },
      { name: "Katihar", headquarters: "Katihar" },
      { name: "East Champaran", headquarters: "Motihari" },
      { name: "West Champaran", headquarters: "Bettiah" },
      { name: "Gopalganj", headquarters: "Gopalganj" },
      { name: "Siwan", headquarters: "Siwan" },
      { name: "Sheohar", headquarters: "Sheohar" },
      { name: "Banka", headquarters: "Banka" },
    ],
    rssKeywords: ["bihar", "patna", "gaya", "बिहार"],
  },
  {
    id: "jharkhand",
    name: "Jharkhand",
    code: "JH",
    type: "state",
    languages: ["hi", "en"],
    capital: "Ranchi",
    color: "bg-yellow-300",
    flagEmoji: "⛏️",
    region: "east",
    cities: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh", "Deoghar", "Giridih", "Ramgarh"],
    districts: [
      { name: "Ranchi", headquarters: "Ranchi" },
      { name: "East Singhbhum", headquarters: "Jamshedpur" },
      { name: "Dhanbad", headquarters: "Dhanbad" },
      { name: "Bokaro", headquarters: "Bokaro" },
      { name: "Hazaribagh", headquarters: "Hazaribagh" },
      { name: "Deoghar", headquarters: "Deoghar" },
      { name: "Giridih", headquarters: "Giridih" },
      { name: "Ramgarh", headquarters: "Ramgarh" },
      { name: "Gumla", headquarters: "Gumla" },
      { name: "Lohardaga", headquarters: "Lohardaga" },
      { name: "Palamu", headquarters: "Daltonganj" },
      { name: "Latehar", headquarters: "Latehar" },
      { name: "Garhwa", headquarters: "Garhwa" },
      { name: "Chatra", headquarters: "Chatra" },
      { name: "Koderma", headquarters: "Koderma" },
      { name: "West Singhbhum", headquarters: "Chaibasa" },
      { name: "Seraikela Kharsawan", headquarters: "Seraikela" },
      { name: "Khunti", headquarters: "Khunti" },
      { name: "Simdega", headquarters: "Simdega" },
      { name: "Pakur", headquarters: "Pakur" },
      { name: "Sahebganj", headquarters: "Sahebganj" },
      { name: "Godda", headquarters: "Godda" },
      { name: "Dumka", headquarters: "Dumka" },
      { name: "Jamtara", headquarters: "Jamtara" },
    ],
    rssKeywords: ["jharkhand", "ranchi", "jamshedpur", "झारखंड"],
  },
  {
    id: "maharashtra",
    name: "Maharashtra",
    code: "MH",
    type: "state",
    languages: ["mr", "en", "hi"],
    capital: "Mumbai",
    color: "bg-pink-400",
    flagEmoji: "🦁",
    region: "west",
    cities: ["Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Kolhapur", "Navi Mumbai", "Amravati"],
    districts: [
      { name: "Mumbai", headquarters: "Mumbai" },
      { name: "Mumbai Suburban", headquarters: "Bandra" },
      { name: "Thane", headquarters: "Thane" },
      { name: "Pune", headquarters: "Pune" },
      { name: "Nagpur", headquarters: "Nagpur" },
      { name: "Nashik", headquarters: "Nashik" },
      { name: "Aurangabad", headquarters: "Aurangabad" },
      { name: "Solapur", headquarters: "Solapur" },
      { name: "Kolhapur", headquarters: "Kolhapur" },
      { name: "Satara", headquarters: "Satara" },
      { name: "Sangli", headquarters: "Sangli" },
      { name: "Ratnagiri", headquarters: "Ratnagiri" },
      { name: "Sindhudurg", headquarters: "Sindhudurg" },
      { name: "Raigad", headquarters: "Alibaug" },
      { name: "Palghar", headquarters: "Palghar" },
      { name: "Ahmednagar", headquarters: "Ahmednagar" },
      { name: "Jalgaon", headquarters: "Jalgaon" },
      { name: "Dhule", headquarters: "Dhule" },
      { name: "Nandurbar", headquarters: "Nandurbar" },
      { name: "Chandrapur", headquarters: "Chandrapur" },
      { name: "Gadchiroli", headquarters: "Gadchiroli" },
      { name: "Gondia", headquarters: "Gondia" },
      { name: "Bhandara", headquarters: "Bhandara" },
      { name: "Wardha", headquarters: "Wardha" },
      { name: "Yavatmal", headquarters: "Yavatmal" },
      { name: "Washim", headquarters: "Washim" },
      { name: "Akola", headquarters: "Akola" },
      { name: "Buldhana", headquarters: "Buldhana" },
      { name: "Amravati", headquarters: "Amravati" },
      { name: "Jalna", headquarters: "Jalna" },
      { name: "Parbhani", headquarters: "Parbhani" },
      { name: "Hingoli", headquarters: "Hingoli" },
      { name: "Nanded", headquarters: "Nanded" },
      { name: "Latur", headquarters: "Latur" },
      { name: "Osmanabad", headquarters: "Osmanabad" },
      { name: "Beed", headquarters: "Beed" },
    ],
    rssKeywords: ["maharashtra", "mumbai", "pune", "marathi", "मराठी"],
  },
  {
    id: "karnataka",
    name: "Karnataka",
    code: "KA",
    type: "state",
    languages: ["kn", "en"],
    capital: "Bengaluru",
    color: "bg-red-500",
    flagEmoji: "🐘",
    region: "south",
    cities: ["Bengaluru", "Mysuru", "Hubli", "Mangaluru", "Belgaum", "Dharwad", "Davangere", "Ballari", "Tumkur", "Shimoga"],
    districts: [
      { name: "Bengaluru Urban", headquarters: "Bengaluru" },
      { name: "Bengaluru Rural", headquarters: "Bengaluru" },
      { name: "Mysuru", headquarters: "Mysuru" },
      { name: "Dharwad", headquarters: "Dharwad" },
      { name: "Belgaum", headquarters: "Belgaum" },
      { name: "Mangaluru", headquarters: "Mangaluru" },
      { name: "Ballari", headquarters: "Ballari" },
      { name: "Tumkur", headquarters: "Tumkur" },
      { name: "Shimoga", headquarters: "Shimoga" },
      { name: "Davangere", headquarters: "Davangere" },
      { name: "Hassan", headquarters: "Hassan" },
      { name: "Mandya", headquarters: "Mandya" },
      { name: "Kolar", headquarters: "Kolar" },
      { name: "Chikkaballapur", headquarters: "Chikkaballapur" },
      { name: "Ramanagara", headquarters: "Ramanagara" },
      { name: "Chitradurga", headquarters: "Chitradurga" },
      { name: "Bidar", headquarters: "Bidar" },
      { name: "Kalaburagi", headquarters: "Kalaburagi" },
      { name: "Raichur", headquarters: "Raichur" },
      { name: "Yadgir", headquarters: "Yadgir" },
      { name: "Koppal", headquarters: "Koppal" },
      { name: "Gadag", headquarters: "Gadag" },
      { name: "Haveri", headquarters: "Haveri" },
      { name: "Uttara Kannada", headquarters: "Karwar" },
      { name: "Udupi", headquarters: "Udupi" },
      { name: "Dakshina Kannada", headquarters: "Mangaluru" },
      { name: "Kodagu", headquarters: "Madikeri" },
      { name: "Chamarajanagar", headquarters: "Chamarajanagar" },
      { name: "Chikkamagaluru", headquarters: "Chikkamagaluru" },
      { name: "Bagalkot", headquarters: "Bagalkot" },
      { name: "Vijayapura", headquarters: "Vijayapura" },
    ],
    rssKeywords: ["karnataka", "bangalore", "bengaluru", "kannada", "ಕನ್ನಡ"],
  },
  {
    id: "tamil-nadu",
    name: "Tamil Nadu",
    code: "TN",
    type: "state",
    languages: ["ta", "en"],
    capital: "Chennai",
    color: "bg-green-600",
    flagEmoji: "🏯",
    region: "south",
    cities: ["Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli", "Tirunelveli", "Erode", "Vellore", "Thoothukudi", "Tiruppur"],
    districts: [
      { name: "Chennai", headquarters: "Chennai" },
      { name: "Coimbatore", headquarters: "Coimbatore" },
      { name: "Madurai", headquarters: "Madurai" },
      { name: "Salem", headquarters: "Salem" },
      { name: "Tiruchirappalli", headquarters: "Tiruchirappalli" },
      { name: "Tirunelveli", headquarters: "Tirunelveli" },
      { name: "Erode", headquarters: "Erode" },
      { name: "Vellore", headquarters: "Vellore" },
      { name: "Thoothukudi", headquarters: "Thoothukudi" },
      { name: "Tiruppur", headquarters: "Tiruppur" },
      { name: "Kancheepuram", headquarters: "Kancheepuram" },
      { name: "Chengalpattu", headquarters: "Chengalpattu" },
      { name: "Tiruvallur", headquarters: "Tiruvallur" },
      { name: "Cuddalore", headquarters: "Cuddalore" },
      { name: "Villupuram", headquarters: "Villupuram" },
      { name: "Thanjavur", headquarters: "Thanjavur" },
      { name: "Nagapattinam", headquarters: "Nagapattinam" },
      { name: "Tiruvarur", headquarters: "Tiruvarur" },
      { name: "Mayiladuthurai", headquarters: "Mayiladuthurai" },
      { name: "Pudukkottai", headquarters: "Pudukkottai" },
      { name: "Karur", headquarters: "Karur" },
      { name: "Dindigul", headquarters: "Dindigul" },
      { name: "Theni", headquarters: "Theni" },
      { name: "Virudhunagar", headquarters: "Virudhunagar" },
      { name: "Sivaganga", headquarters: "Sivaganga" },
      { name: "Ramanathapuram", headquarters: "Ramanathapuram" },
      { name: "Namakkal", headquarters: "Namakkal" },
      { name: "Dharmapuri", headquarters: "Dharmapuri" },
      { name: "Krishnagiri", headquarters: "Krishnagiri" },
      { name: "Tirupattur", headquarters: "Tirupattur" },
      { name: "Ranipet", headquarters: "Ranipet" },
      { name: "Tiruvannamalai", headquarters: "Tiruvannamalai" },
      { name: "Kallakurichi", headquarters: "Kallakurichi" },
      { name: "Ariyalur", headquarters: "Ariyalur" },
      { name: "Perambalur", headquarters: "Perambalur" },
      { name: "Nilgiris", headquarters: "Udhagamandalam" },
      { name: "Kanyakumari", headquarters: "Nagercoil" },
      { name: "Tenkasi", headquarters: "Tenkasi" },
    ],
    rssKeywords: ["tamil", "tamilnadu", "chennai", "தமிழ்"],
  },
  {
    id: "kerala",
    name: "Kerala",
    code: "KL",
    type: "state",
    languages: ["ml", "en"],
    capital: "Thiruvananthapuram",
    color: "bg-teal-600",
    flagEmoji: "🌴",
    region: "south",
    cities: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Kannur", "Palakkad", "Alappuzha", "Malappuram", "Kottayam"],
    districts: [
      { name: "Thiruvananthapuram", headquarters: "Thiruvananthapuram" },
      { name: "Kollam", headquarters: "Kollam" },
      { name: "Pathanamthitta", headquarters: "Pathanamthitta" },
      { name: "Alappuzha", headquarters: "Alappuzha" },
      { name: "Kottayam", headquarters: "Kottayam" },
      { name: "Idukki", headquarters: "Painavu" },
      { name: "Ernakulam", headquarters: "Kochi" },
      { name: "Thrissur", headquarters: "Thrissur" },
      { name: "Palakkad", headquarters: "Palakkad" },
      { name: "Malappuram", headquarters: "Malappuram" },
      { name: "Kozhikode", headquarters: "Kozhikode" },
      { name: "Wayanad", headquarters: "Kalpetta" },
      { name: "Kannur", headquarters: "Kannur" },
      { name: "Kasaragod", headquarters: "Kasaragod" },
    ],
    rssKeywords: ["kerala", "kochi", "malayalam", "മലയാളം"],
  },
  {
    id: "andhra-pradesh",
    name: "Andhra Pradesh",
    code: "AP",
    type: "state",
    languages: ["te", "en"],
    capital: "Amaravati",
    color: "bg-purple-500",
    flagEmoji: "🏯",
    region: "south",
    cities: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati", "Kurnool", "Rajahmundry", "Kakinada", "Kadapa", "Anantapur"],
    districts: [
      { name: "Visakhapatnam", headquarters: "Visakhapatnam" },
      { name: "Vijayawada", headquarters: "Vijayawada" },
      { name: "Guntur", headquarters: "Guntur" },
      { name: "Krishna", headquarters: "Machilipatnam" },
      { name: "East Godavari", headquarters: "Kakinada" },
      { name: "West Godavari", headquarters: "Eluru" },
      { name: "Nellore", headquarters: "Nellore" },
      { name: "Prakasam", headquarters: "Ongole" },
      { name: "Kurnool", headquarters: "Kurnool" },
      { name: "Anantapur", headquarters: "Anantapur" },
      { name: "Kadapa", headquarters: "Kadapa" },
      { name: "Chittoor", headquarters: "Chittoor" },
      { name: "Srikakulam", headquarters: "Srikakulam" },
      { name: "Vizianagaram", headquarters: "Vizianagaram" },
      { name: "Parvathipuram Manyam", headquarters: "Parvathipuram" },
      { name: "Alluri Sitharama Raju", headquarters: "Paderu" },
      { name: "Anakapalli", headquarters: "Anakapalli" },
      { name: "Kakinada", headquarters: "Kakinada" },
      { name: "Konaseema", headquarters: "Amalapuram" },
      { name: "Eluru", headquarters: "Eluru" },
      { name: "NTR", headquarters: "Vijayawada" },
      { name: "Palnadu", headquarters: "Narasaraopet" },
      { name: "Bapatla", headquarters: "Bapatla" },
      { name: "Nandyal", headquarters: "Nandyal" },
      { name: "Annamayya", headquarters: "Rayachoti" },
      { name: "Tirupati", headquarters: "Tirupati" },
    ],
    rssKeywords: ["andhra", "vizag", "visakhapatnam", "telugu", "తెలుగు"],
  },
  {
    id: "telangana",
    name: "Telangana",
    code: "TS",
    type: "state",
    languages: ["te", "en"],
    capital: "Hyderabad",
    color: "bg-purple-400",
    flagEmoji: "🏰",
    region: "south",
    cities: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Ramagundam", "Mahbubnagar", "Nalgonda", "Adilabad", "Secunderabad"],
    districts: [
      { name: "Hyderabad", headquarters: "Hyderabad" },
      { name: "Rangareddy", headquarters: "Shamshabad" },
      { name: "Medchal-Malkajgiri", headquarters: "Medchal" },
      { name: "Sangareddy", headquarters: "Sangareddy" },
      { name: "Warangal Urban", headquarters: "Warangal" },
      { name: "Warangal Rural", headquarters: "Warangal" },
      { name: "Karimnagar", headquarters: "Karimnagar" },
      { name: "Nizamabad", headquarters: "Nizamabad" },
      { name: "Khammam", headquarters: "Khammam" },
      { name: "Nalgonda", headquarters: "Nalgonda" },
      { name: "Mahbubnagar", headquarters: "Mahbubnagar" },
      { name: "Adilabad", headquarters: "Adilabad" },
      { name: "Jagitial", headquarters: "Jagitial" },
      { name: "Peddapalli", headquarters: "Peddapalli" },
      { name: "Siddipet", headquarters: "Siddipet" },
      { name: "Medak", headquarters: "Medak" },
      { name: "Kamareddy", headquarters: "Kamareddy" },
      { name: "Mancherial", headquarters: "Mancherial" },
      { name: "Nirmal", headquarters: "Nirmal" },
      { name: "Kumuram Bheem", headquarters: "Asifabad" },
      { name: "Jagtial", headquarters: "Jagtial" },
      { name: "Rajanna Sircilla", headquarters: "Sircilla" },
      { name: "Bhadradri Kothagudem", headquarters: "Kothagudem" },
      { name: "Mahabubabad", headquarters: "Mahabubabad" },
      { name: "Jayashankar Bhupalpally", headquarters: "Bhupalpally" },
      { name: "Mulugu", headquarters: "Mulugu" },
      { name: "Suryapet", headquarters: "Suryapet" },
      { name: "Yadadri Bhuvanagiri", headquarters: "Bhongir" },
      { name: "Jangaon", headquarters: "Jangaon" },
      { name: "Narayanpet", headquarters: "Narayanpet" },
      { name: "Jogulamba Gadwal", headquarters: "Gadwal" },
      { name: "Wanaparthy", headquarters: "Wanaparthy" },
      { name: "Nagarkurnool", headquarters: "Nagarkurnool" },
      { name: "Vikarabad", headquarters: "Vikarabad" },
    ],
    rssKeywords: ["telangana", "hyderabad", "తెలంగాణ"],
  },
  {
    id: "gujarat",
    name: "Gujarat",
    code: "GJ",
    type: "state",
    languages: ["gu", "en", "hi"],
    capital: "Gandhinagar",
    color: "bg-indigo-500",
    flagEmoji: "🦁",
    region: "west",
    cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Junagadh", "Anand", "Navsari"],
    districts: [
      { name: "Ahmedabad", headquarters: "Ahmedabad" },
      { name: "Surat", headquarters: "Surat" },
      { name: "Vadodara", headquarters: "Vadodara" },
      { name: "Rajkot", headquarters: "Rajkot" },
      { name: "Bhavnagar", headquarters: "Bhavnagar" },
      { name: "Jamnagar", headquarters: "Jamnagar" },
      { name: "Gandhinagar", headquarters: "Gandhinagar" },
      { name: "Junagadh", headquarters: "Junagadh" },
      { name: "Kutch", headquarters: "Bhuj" },
      { name: "Anand", headquarters: "Anand" },
      { name: "Kheda", headquarters: "Nadiad" },
      { name: "Panchmahal", headquarters: "Godhra" },
      { name: "Dahod", headquarters: "Dahod" },
      { name: "Mahisagar", headquarters: "Lunavada" },
      { name: "Sabarkantha", headquarters: "Himatnagar" },
      { name: "Aravalli", headquarters: "Modasa" },
      { name: "Banaskantha", headquarters: "Palanpur" },
      { name: "Mehsana", headquarters: "Mehsana" },
      { name: "Patan", headquarters: "Patan" },
      { name: "Surendranagar", headquarters: "Surendranagar" },
      { name: "Morbi", headquarters: "Morbi" },
      { name: "Devbhoomi Dwarka", headquarters: "Khambhalia" },
      { name: "Porbandar", headquarters: "Porbandar" },
      { name: "Gir Somnath", headquarters: "Veraval" },
      { name: "Amreli", headquarters: "Amreli" },
      { name: "Botad", headquarters: "Botad" },
      { name: "Bharuch", headquarters: "Bharuch" },
      { name: "Narmada", headquarters: "Rajpipla" },
      { name: "Tapi", headquarters: "Vyara" },
      { name: "Navsari", headquarters: "Navsari" },
      { name: "Valsad", headquarters: "Valsad" },
      { name: "Dangs", headquarters: "Ahwa" },
      { name: "Chhota Udaipur", headquarters: "Chhota Udaipur" },
    ],
    rssKeywords: ["gujarat", "ahmedabad", "surat", "gujarati", "ગુજરાતી"],
  },
  {
    id: "rajasthan",
    name: "Rajasthan",
    code: "RJ",
    type: "state",
    languages: ["hi", "en"],
    capital: "Jaipur",
    color: "bg-pink-500",
    flagEmoji: "🐫",
    region: "west",
    cities: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner", "Ajmer", "Bhilwara", "Alwar", "Bharatpur", "Sikar"],
    districts: [
      { name: "Jaipur", headquarters: "Jaipur" },
      { name: "Jodhpur", headquarters: "Jodhpur" },
      { name: "Udaipur", headquarters: "Udaipur" },
      { name: "Kota", headquarters: "Kota" },
      { name: "Bikaner", headquarters: "Bikaner" },
      { name: "Ajmer", headquarters: "Ajmer" },
      { name: "Bhilwara", headquarters: "Bhilwara" },
      { name: "Alwar", headquarters: "Alwar" },
      { name: "Bharatpur", headquarters: "Bharatpur" },
      { name: "Sikar", headquarters: "Sikar" },
      { name: "Nagaur", headquarters: "Nagaur" },
      { name: "Pali", headquarters: "Pali" },
      { name: "Barmer", headquarters: "Barmer" },
      { name: "Jaisalmer", headquarters: "Jaisalmer" },
      { name: "Churu", headquarters: "Churu" },
      { name: "Jhunjhunu", headquarters: "Jhunjhunu" },
      { name: "Tonk", headquarters: "Tonk" },
      { name: "Sawai Madhopur", headquarters: "Sawai Madhopur" },
      { name: "Karauli", headquarters: "Karauli" },
      { name: "Dausa", headquarters: "Dausa" },
      { name: "Dholpur", headquarters: "Dholpur" },
      { name: "Bundi", headquarters: "Bundi" },
      { name: "Baran", headquarters: "Baran" },
      { name: "Jhalawar", headquarters: "Jhalawar" },
      { name: "Chittorgarh", headquarters: "Chittorgarh" },
      { name: "Pratapgarh", headquarters: "Pratapgarh" },
      { name: "Rajsamand", headquarters: "Rajsamand" },
      { name: "Dungarpur", headquarters: "Dungarpur" },
      { name: "Banswara", headquarters: "Banswara" },
      { name: "Sirohi", headquarters: "Sirohi" },
      { name: "Jalore", headquarters: "Jalore" },
      { name: "Hanumangarh", headquarters: "Hanumangarh" },
      { name: "Sri Ganganagar", headquarters: "Sri Ganganagar" },
    ],
    rssKeywords: ["rajasthan", "jaipur", "jodhpur", "राजस्थान"],
  },
  {
    id: "uttar-pradesh",
    name: "Uttar Pradesh",
    code: "UP",
    type: "state",
    languages: ["hi", "en"],
    capital: "Lucknow",
    color: "bg-orange-400",
    flagEmoji: "🕌",
    region: "north",
    cities: ["Lucknow", "Kanpur", "Agra", "Varanasi", "Noida", "Ghaziabad", "Prayagraj", "Meerut", "Bareilly", "Aligarh"],
    districts: [
      { name: "Lucknow", headquarters: "Lucknow" },
      { name: "Kanpur Nagar", headquarters: "Kanpur" },
      { name: "Agra", headquarters: "Agra" },
      { name: "Varanasi", headquarters: "Varanasi" },
      { name: "Gautam Buddha Nagar", headquarters: "Noida" },
      { name: "Ghaziabad", headquarters: "Ghaziabad" },
      { name: "Prayagraj", headquarters: "Prayagraj" },
      { name: "Meerut", headquarters: "Meerut" },
      { name: "Bareilly", headquarters: "Bareilly" },
      { name: "Aligarh", headquarters: "Aligarh" },
      { name: "Moradabad", headquarters: "Moradabad" },
      { name: "Gorakhpur", headquarters: "Gorakhpur" },
      { name: "Saharanpur", headquarters: "Saharanpur" },
      { name: "Mathura", headquarters: "Mathura" },
      { name: "Firozabad", headquarters: "Firozabad" },
      { name: "Bulandshahr", headquarters: "Bulandshahr" },
      { name: "Hapur", headquarters: "Hapur" },
      { name: "Muzaffarnagar", headquarters: "Muzaffarnagar" },
      { name: "Shamli", headquarters: "Shamli" },
      { name: "Baghpat", headquarters: "Baghpat" },
      { name: "Jhansi", headquarters: "Jhansi" },
      { name: "Lalitpur", headquarters: "Lalitpur" },
      { name: "Jalaun", headquarters: "Orai" },
      { name: "Hamirpur", headquarters: "Hamirpur" },
      { name: "Mahoba", headquarters: "Mahoba" },
      { name: "Banda", headquarters: "Banda" },
      { name: "Chitrakoot", headquarters: "Chitrakoot" },
      { name: "Fatehpur", headquarters: "Fatehpur" },
      { name: "Kaushambi", headquarters: "Manjhanpur" },
      { name: "Pratapgarh", headquarters: "Pratapgarh" },
      { name: "Amethi", headquarters: "Gauriganj" },
      { name: "Sultanpur", headquarters: "Sultanpur" },
      { name: "Ambedkar Nagar", headquarters: "Akbarpur" },
      { name: "Ayodhya", headquarters: "Ayodhya" },
      { name: "Barabanki", headquarters: "Barabanki" },
      { name: "Bahraich", headquarters: "Bahraich" },
      { name: "Shravasti", headquarters: "Bhinga" },
      { name: "Balrampur", headquarters: "Balrampur" },
      { name: "Gonda", headquarters: "Gonda" },
      { name: "Basti", headquarters: "Basti" },
      { name: "Sant Kabir Nagar", headquarters: "Khalilabad" },
      { name: "Siddharthnagar", headquarters: "Siddharthnagar" },
      { name: "Maharajganj", headquarters: "Maharajganj" },
      { name: "Kushinagar", headquarters: "Kushinagar" },
      { name: "Deoria", headquarters: "Deoria" },
      { name: "Azamgarh", headquarters: "Azamgarh" },
      { name: "Mau", headquarters: "Mau" },
      { name: "Ballia", headquarters: "Ballia" },
      { name: "Ghazipur", headquarters: "Ghazipur" },
      { name: "Chandauli", headquarters: "Chandauli" },
      { name: "Jaunpur", headquarters: "Jaunpur" },
      { name: "Bhadohi", headquarters: "Bhadohi" },
      { name: "Mirzapur", headquarters: "Mirzapur" },
      { name: "Sonbhadra", headquarters: "Robertsganj" },
      { name: "Unnao", headquarters: "Unnao" },
      { name: "Rae Bareli", headquarters: "Rae Bareli" },
      { name: "Hardoi", headquarters: "Hardoi" },
      { name: "Lakhimpur Kheri", headquarters: "Lakhimpur" },
      { name: "Sitapur", headquarters: "Sitapur" },
      { name: "Shahjahanpur", headquarters: "Shahjahanpur" },
      { name: "Pilibhit", headquarters: "Pilibhit" },
      { name: "Rampur", headquarters: "Rampur" },
      { name: "Bijnor", headquarters: "Bijnor" },
      { name: "Amroha", headquarters: "Amroha" },
      { name: "Sambhal", headquarters: "Sambhal" },
      { name: "Budaun", headquarters: "Budaun" },
      { name: "Auraiya", headquarters: "Auraiya" },
      { name: "Kannauj", headquarters: "Kannauj" },
      { name: "Etawah", headquarters: "Etawah" },
      { name: "Farrukhabad", headquarters: "Fatehgarh" },
      { name: "Kanpur Dehat", headquarters: "Akbarpur" },
      { name: "Mainpuri", headquarters: "Mainpuri" },
      { name: "Etah", headquarters: "Etah" },
      { name: "Kasganj", headquarters: "Kasganj" },
      { name: "Hathras", headquarters: "Hathras" },
    ],
    rssKeywords: ["uttar pradesh", "up", "lucknow", "varanasi", "उत्तर प्रदेश"],
  },
  {
    id: "madhya-pradesh",
    name: "Madhya Pradesh",
    code: "MP",
    type: "state",
    languages: ["hi", "en"],
    capital: "Bhopal",
    color: "bg-violet-500",
    flagEmoji: "🐅",
    region: "central",
    cities: ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Satna", "Rewa", "Ratlam", "Dewas"],
    districts: [
      { name: "Bhopal", headquarters: "Bhopal" },
      { name: "Indore", headquarters: "Indore" },
      { name: "Jabalpur", headquarters: "Jabalpur" },
      { name: "Gwalior", headquarters: "Gwalior" },
      { name: "Ujjain", headquarters: "Ujjain" },
      { name: "Sagar", headquarters: "Sagar" },
      { name: "Satna", headquarters: "Satna" },
      { name: "Rewa", headquarters: "Rewa" },
      { name: "Ratlam", headquarters: "Ratlam" },
      { name: "Dewas", headquarters: "Dewas" },
      { name: "Chhindwara", headquarters: "Chhindwara" },
      { name: "Betul", headquarters: "Betul" },
      { name: "Hoshangabad", headquarters: "Hoshangabad" },
      { name: "Sehore", headquarters: "Sehore" },
      { name: "Raisen", headquarters: "Raisen" },
      { name: "Vidisha", headquarters: "Vidisha" },
      { name: "Damoh", headquarters: "Damoh" },
      { name: "Panna", headquarters: "Panna" },
      { name: "Chhatarpur", headquarters: "Chhatarpur" },
      { name: "Tikamgarh", headquarters: "Tikamgarh" },
      { name: "Niwari", headquarters: "Niwari" },
      { name: "Datia", headquarters: "Datia" },
      { name: "Shivpuri", headquarters: "Shivpuri" },
      { name: "Ashoknagar", headquarters: "Ashoknagar" },
      { name: "Guna", headquarters: "Guna" },
      { name: "Morena", headquarters: "Morena" },
      { name: "Bhind", headquarters: "Bhind" },
      { name: "Mandsaur", headquarters: "Mandsaur" },
      { name: "Neemuch", headquarters: "Neemuch" },
      { name: "Shajapur", headquarters: "Shajapur" },
      { name: "Agar Malwa", headquarters: "Agar" },
      { name: "Dhar", headquarters: "Dhar" },
      { name: "Jhabua", headquarters: "Jhabua" },
      { name: "Alirajpur", headquarters: "Alirajpur" },
      { name: "Barwani", headquarters: "Barwani" },
      { name: "Khargone", headquarters: "Khargone" },
      { name: "Khandwa", headquarters: "Khandwa" },
      { name: "Burhanpur", headquarters: "Burhanpur" },
      { name: "Harda", headquarters: "Harda" },
      { name: "Narsinghpur", headquarters: "Narsinghpur" },
      { name: "Mandla", headquarters: "Mandla" },
      { name: "Dindori", headquarters: "Dindori" },
      { name: "Balaghat", headquarters: "Balaghat" },
      { name: "Seoni", headquarters: "Seoni" },
      { name: "Katni", headquarters: "Katni" },
      { name: "Umaria", headquarters: "Umaria" },
      { name: "Shahdol", headquarters: "Shahdol" },
      { name: "Anuppur", headquarters: "Anuppur" },
      { name: "Sidhi", headquarters: "Sidhi" },
      { name: "Singrauli", headquarters: "Waidhan" },
      { name: "Maihar", headquarters: "Maihar" },
    ],
    rssKeywords: ["madhya pradesh", "mp", "bhopal", "indore", "मध्य प्रदेश"],
  },
  {
    id: "chhattisgarh",
    name: "Chhattisgarh",
    code: "CG",
    type: "state",
    languages: ["hi", "en"],
    capital: "Raipur",
    color: "bg-violet-400",
    flagEmoji: "🌾",
    region: "central",
    cities: ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon", "Jagdalpur", "Raigarh", "Ambikapur", "Dhamtari"],
    districts: [
      { name: "Raipur", headquarters: "Raipur" },
      { name: "Durg", headquarters: "Durg" },
      { name: "Bilaspur", headquarters: "Bilaspur" },
      { name: "Korba", headquarters: "Korba" },
      { name: "Rajnandgaon", headquarters: "Rajnandgaon" },
      { name: "Bastar", headquarters: "Jagdalpur" },
      { name: "Raigarh", headquarters: "Raigarh" },
      { name: "Surguja", headquarters: "Ambikapur" },
      { name: "Dhamtari", headquarters: "Dhamtari" },
      { name: "Janjgir-Champa", headquarters: "Janjgir" },
      { name: "Mahasamund", headquarters: "Mahasamund" },
      { name: "Kawardha", headquarters: "Kawardha" },
      { name: "Balod", headquarters: "Balod" },
      { name: "Bemetara", headquarters: "Bemetara" },
      { name: "Baloda Bazar", headquarters: "Baloda Bazar" },
      { name: "Gariaband", headquarters: "Gariaband" },
      { name: "Mungeli", headquarters: "Mungeli" },
      { name: "Balrampur", headquarters: "Balrampur" },
      { name: "Surajpur", headquarters: "Surajpur" },
      { name: "Jashpur", headquarters: "Jashpur Nagar" },
      { name: "Koriya", headquarters: "Baikunthpur" },
      { name: "Kondagaon", headquarters: "Kondagaon" },
      { name: "Narayanpur", headquarters: "Narayanpur" },
      { name: "Kanker", headquarters: "Kanker" },
      { name: "Dantewada", headquarters: "Dantewada" },
      { name: "Bijapur", headquarters: "Bijapur" },
      { name: "Sukma", headquarters: "Sukma" },
      { name: "Gaurela-Pendra-Marwahi", headquarters: "Gaurela" },
      { name: "Manendragarh", headquarters: "Manendragarh" },
      { name: "Khairagarh-Chhuikhadan-Gandai", headquarters: "Khairagarh" },
      { name: "Mohla-Manpur", headquarters: "Mohla Manpur" },
      { name: "Sarangarh-Bilaigarh", headquarters: "Sarangarh" },
      { name: "Shakti", headquarters: "Shakti" },
    ],
    rssKeywords: ["chhattisgarh", "raipur", "छत्तीसगढ़"],
  },
  {
    id: "punjab",
    name: "Punjab",
    code: "PB",
    type: "state",
    languages: ["pa", "en", "hi"],
    capital: "Chandigarh",
    color: "bg-amber-400",
    flagEmoji: "🌾",
    region: "north",
    cities: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Pathankot", "Hoshiarpur", "Moga", "Firozpur"],
    districts: [
      { name: "Ludhiana", headquarters: "Ludhiana" },
      { name: "Amritsar", headquarters: "Amritsar" },
      { name: "Jalandhar", headquarters: "Jalandhar" },
      { name: "Patiala", headquarters: "Patiala" },
      { name: "Bathinda", headquarters: "Bathinda" },
      { name: "SAS Nagar (Mohali)", headquarters: "Mohali" },
      { name: "Pathankot", headquarters: "Pathankot" },
      { name: "Hoshiarpur", headquarters: "Hoshiarpur" },
      { name: "Moga", headquarters: "Moga" },
      { name: "Firozpur", headquarters: "Firozpur" },
      { name: "Gurdaspur", headquarters: "Gurdaspur" },
      { name: "Kapurthala", headquarters: "Kapurthala" },
      { name: "Fazilka", headquarters: "Fazilka" },
      { name: "Sri Muktsar Sahib", headquarters: "Muktsar" },
      { name: "Faridkot", headquarters: "Faridkot" },
      { name: "Sangrur", headquarters: "Sangrur" },
      { name: "Malerkotla", headquarters: "Malerkotla" },
      { name: "Barnala", headquarters: "Barnala" },
      { name: "Mansa", headquarters: "Mansa" },
      { name: "Fatehgarh Sahib", headquarters: "Fatehgarh Sahib" },
      { name: "Rupnagar", headquarters: "Rupnagar" },
      { name: "Shaheed Bhagat Singh Nagar", headquarters: "Nawanshahr" },
    ],
    rssKeywords: ["punjab", "punjabi", "ludhiana", "amritsar", "ਪੰਜਾਬੀ"],
  },
  {
    id: "haryana",
    name: "Haryana",
    code: "HR",
    type: "state",
    languages: ["hi", "en"],
    capital: "Chandigarh",
    color: "bg-amber-500",
    flagEmoji: "🌾",
    region: "north",
    cities: ["Faridabad", "Gurgaon", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Hisar", "Karnal", "Sonipat", "Panchkula"],
    districts: [
      { name: "Faridabad", headquarters: "Faridabad" },
      { name: "Gurugram", headquarters: "Gurugram" },
      { name: "Panipat", headquarters: "Panipat" },
      { name: "Ambala", headquarters: "Ambala" },
      { name: "Yamunanagar", headquarters: "Yamunanagar" },
      { name: "Rohtak", headquarters: "Rohtak" },
      { name: "Hisar", headquarters: "Hisar" },
      { name: "Karnal", headquarters: "Karnal" },
      { name: "Sonipat", headquarters: "Sonipat" },
      { name: "Panchkula", headquarters: "Panchkula" },
      { name: "Jhajjar", headquarters: "Jhajjar" },
      { name: "Rewari", headquarters: "Rewari" },
      { name: "Mahendragarh", headquarters: "Narnaul" },
      { name: "Bhiwani", headquarters: "Bhiwani" },
      { name: "Charkhi Dadri", headquarters: "Charkhi Dadri" },
      { name: "Jind", headquarters: "Jind" },
      { name: "Kaithal", headquarters: "Kaithal" },
      { name: "Kurukshetra", headquarters: "Kurukshetra" },
      { name: "Sirsa", headquarters: "Sirsa" },
      { name: "Fatehabad", headquarters: "Fatehabad" },
      { name: "Palwal", headquarters: "Palwal" },
      { name: "Nuh", headquarters: "Nuh" },
    ],
    rssKeywords: ["haryana", "gurgaon", "gurugram", "faridabad", "हरियाणा"],
  },
  {
    id: "himachal-pradesh",
    name: "Himachal Pradesh",
    code: "HP",
    type: "state",
    languages: ["hi", "en"],
    capital: "Shimla",
    color: "bg-amber-300",
    flagEmoji: "🏔️",
    region: "north",
    cities: ["Shimla", "Dharamshala", "Manali", "Solan", "Mandi", "Kullu", "Palampur", "Baddi", "Nahan", "Hamirpur"],
    districts: [
      { name: "Shimla", headquarters: "Shimla" },
      { name: "Kangra", headquarters: "Dharamshala" },
      { name: "Kullu", headquarters: "Kullu" },
      { name: "Solan", headquarters: "Solan" },
      { name: "Mandi", headquarters: "Mandi" },
      { name: "Una", headquarters: "Una" },
      { name: "Hamirpur", headquarters: "Hamirpur" },
      { name: "Bilaspur", headquarters: "Bilaspur" },
      { name: "Sirmaur", headquarters: "Nahan" },
      { name: "Chamba", headquarters: "Chamba" },
      { name: "Kinnaur", headquarters: "Reckong Peo" },
      { name: "Lahaul and Spiti", headquarters: "Keylong" },
    ],
    rssKeywords: ["himachal", "shimla", "manali", "हिमाचल"],
  },
  {
    id: "uttarakhand",
    name: "Uttarakhand",
    code: "UK",
    type: "state",
    languages: ["hi", "en"],
    capital: "Dehradun",
    color: "bg-orange-300",
    flagEmoji: "🏔️",
    region: "north",
    cities: ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Haldwani", "Roorkee", "Rudrapur", "Kashipur", "Ramnagar", "Mussoorie"],
    districts: [
      { name: "Dehradun", headquarters: "Dehradun" },
      { name: "Haridwar", headquarters: "Haridwar" },
      { name: "Nainital", headquarters: "Nainital" },
      { name: "Udham Singh Nagar", headquarters: "Rudrapur" },
      { name: "Almora", headquarters: "Almora" },
      { name: "Pithoragarh", headquarters: "Pithoragarh" },
      { name: "Champawat", headquarters: "Champawat" },
      { name: "Bageshwar", headquarters: "Bageshwar" },
      { name: "Tehri Garhwal", headquarters: "New Tehri" },
      { name: "Pauri Garhwal", headquarters: "Pauri" },
      { name: "Chamoli", headquarters: "Gopeshwar" },
      { name: "Rudraprayag", headquarters: "Rudraprayag" },
      { name: "Uttarkashi", headquarters: "Uttarkashi" },
    ],
    rssKeywords: ["uttarakhand", "dehradun", "haridwar", "rishikesh", "उत्तराखंड"],
  },
  {
    id: "goa",
    name: "Goa",
    code: "GA",
    type: "state",
    languages: ["en", "mr", "kn"],
    capital: "Panaji",
    color: "bg-red-400",
    flagEmoji: "🏖️",
    region: "west",
    cities: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Calangute", "Candolim", "Anjuna"],
    districts: [
      { name: "North Goa", headquarters: "Panaji" },
      { name: "South Goa", headquarters: "Margao" },
    ],
    rssKeywords: ["goa", "panaji", "margao", "konkani"],
  },
  {
    id: "assam",
    name: "Assam",
    code: "AS",
    type: "state",
    languages: ["as", "en", "bn"],
    capital: "Dispur",
    color: "bg-emerald-500",
    flagEmoji: "🦏",
    region: "northeast",
    cities: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia", "Tezpur", "Karimganj", "Bongaigaon", "Sivasagar"],
    districts: [
      { name: "Kamrup Metropolitan", headquarters: "Guwahati" },
      { name: "Kamrup", headquarters: "Amingaon" },
      { name: "Cachar", headquarters: "Silchar" },
      { name: "Dibrugarh", headquarters: "Dibrugarh" },
      { name: "Jorhat", headquarters: "Jorhat" },
      { name: "Nagaon", headquarters: "Nagaon" },
      { name: "Tinsukia", headquarters: "Tinsukia" },
      { name: "Sonitpur", headquarters: "Tezpur" },
      { name: "Karimganj", headquarters: "Karimganj" },
      { name: "Bongaigaon", headquarters: "Bongaigaon" },
      { name: "Sivasagar", headquarters: "Sivasagar" },
      { name: "Goalpara", headquarters: "Goalpara" },
      { name: "Dhubri", headquarters: "Dhubri" },
      { name: "Kokrajhar", headquarters: "Kokrajhar" },
      { name: "Barpeta", headquarters: "Barpeta" },
      { name: "Nalbari", headquarters: "Nalbari" },
      { name: "Darrang", headquarters: "Mangaldoi" },
      { name: "Udalguri", headquarters: "Udalguri" },
      { name: "Baksa", headquarters: "Mushalpur" },
      { name: "Chirang", headquarters: "Kajalgaon" },
      { name: "Golaghat", headquarters: "Golaghat" },
      { name: "Karbi Anglong", headquarters: "Diphu" },
      { name: "Dima Hasao", headquarters: "Haflong" },
      { name: "Morigaon", headquarters: "Morigaon" },
      { name: "Hojai", headquarters: "Hojai" },
      { name: "Lakhimpur", headquarters: "North Lakhimpur" },
      { name: "Dhemaji", headquarters: "Dhemaji" },
      { name: "Charaideo", headquarters: "Sonari" },
      { name: "Majuli", headquarters: "Garamur" },
      { name: "Biswanath", headquarters: "Biswanath Chariali" },
      { name: "Hailakandi", headquarters: "Hailakandi" },
      { name: "South Salmara-Mankachar", headquarters: "Hatsingimari" },
      { name: "West Karbi Anglong", headquarters: "Hamren" },
      { name: "Bajali", headquarters: "Pathsala" },
      { name: "Tamulpur", headquarters: "Tamulpur" },
    ],
    rssKeywords: ["assam", "guwahati", "assamese", "অসমীয়া"],
  },
  {
    id: "sikkim",
    name: "Sikkim",
    code: "SK",
    type: "state",
    languages: ["en", "ne"],
    capital: "Gangtok",
    color: "bg-yellow-600",
    flagEmoji: "🏔️",
    region: "northeast",
    cities: ["Gangtok", "Namchi", "Pelling", "Gyalshing", "Mangan", "Ravangla"],
    districts: [
      { name: "Gangtok", headquarters: "Gangtok" },
      { name: "Namchi", headquarters: "Namchi" },
      { name: "Gyalshing", headquarters: "Gyalshing" },
      { name: "Mangan", headquarters: "Mangan" },
      { name: "Pakyong", headquarters: "Pakyong" },
      { name: "Soreng", headquarters: "Soreng" },
    ],
    rssKeywords: ["sikkim", "gangtok"],
  },
  {
    id: "arunachal-pradesh",
    name: "Arunachal Pradesh",
    code: "AR",
    type: "state",
    languages: ["en"],
    capital: "Itanagar",
    color: "bg-emerald-400",
    flagEmoji: "🌄",
    region: "northeast",
    cities: ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Bomdila", "Tezu", "Roing"],
    districts: [
      { name: "Papum Pare", headquarters: "Yupia" },
      { name: "Capital Complex", headquarters: "Itanagar" },
      { name: "East Siang", headquarters: "Pasighat" },
      { name: "Tawang", headquarters: "Tawang" },
      { name: "West Kameng", headquarters: "Bomdila" },
      { name: "Lower Subansiri", headquarters: "Ziro" },
      { name: "Upper Subansiri", headquarters: "Daporijo" },
      { name: "West Siang", headquarters: "Aalo" },
      { name: "Upper Siang", headquarters: "Yingkiong" },
      { name: "Lower Dibang Valley", headquarters: "Roing" },
      { name: "Dibang Valley", headquarters: "Anini" },
      { name: "Lohit", headquarters: "Tezu" },
      { name: "Namsai", headquarters: "Namsai" },
      { name: "Anjaw", headquarters: "Hawai" },
      { name: "Changlang", headquarters: "Changlang" },
      { name: "Tirap", headquarters: "Khonsa" },
      { name: "Longding", headquarters: "Longding" },
      { name: "East Kameng", headquarters: "Seppa" },
      { name: "Kurung Kumey", headquarters: "Koloriang" },
      { name: "Kra Daadi", headquarters: "Jamin" },
      { name: "Lower Siang", headquarters: "Likabali" },
      { name: "Lepa Rada", headquarters: "Basar" },
      { name: "Shi Yomi", headquarters: "Mechuka" },
      { name: "Siang", headquarters: "Boleng" },
      { name: "Pakke Kessang", headquarters: "Lemmi" },
    ],
    rssKeywords: ["arunachal", "itanagar"],
  },
  {
    id: "manipur",
    name: "Manipur",
    code: "MN",
    type: "state",
    languages: ["en", "mni"],
    capital: "Imphal",
    color: "bg-emerald-300",
    flagEmoji: "🌺",
    region: "northeast",
    cities: ["Imphal", "Thoubal", "Kakching", "Ukhrul", "Churachandpur", "Bishnupur", "Senapati"],
    districts: [
      { name: "Imphal West", headquarters: "Imphal" },
      { name: "Imphal East", headquarters: "Porompat" },
      { name: "Thoubal", headquarters: "Thoubal" },
      { name: "Kakching", headquarters: "Kakching" },
      { name: "Bishnupur", headquarters: "Bishnupur" },
      { name: "Churachandpur", headquarters: "Churachandpur" },
      { name: "Ukhrul", headquarters: "Ukhrul" },
      { name: "Senapati", headquarters: "Senapati" },
      { name: "Tamenglong", headquarters: "Tamenglong" },
      { name: "Chandel", headquarters: "Chandel" },
      { name: "Jiribam", headquarters: "Jiribam" },
      { name: "Kangpokpi", headquarters: "Kangpokpi" },
      { name: "Noney", headquarters: "Noney" },
      { name: "Pherzawl", headquarters: "Pherzawl" },
      { name: "Tengnoupal", headquarters: "Tengnoupal" },
      { name: "Kamjong", headquarters: "Kamjong" },
    ],
    rssKeywords: ["manipur", "imphal", "মণিপুর"],
  },
  {
    id: "meghalaya",
    name: "Meghalaya",
    code: "ML",
    type: "state",
    languages: ["en", "kha"],
    capital: "Shillong",
    color: "bg-teal-500",
    flagEmoji: "☁️",
    region: "northeast",
    cities: ["Shillong", "Tura", "Nongstoin", "Jowai", "Nongpoh", "Williamnagar", "Baghmara"],
    districts: [
      { name: "East Khasi Hills", headquarters: "Shillong" },
      { name: "West Khasi Hills", headquarters: "Nongstoin" },
      { name: "South West Khasi Hills", headquarters: "Mawkyrwat" },
      { name: "Eastern West Khasi Hills", headquarters: "Mairang" },
      { name: "Ri Bhoi", headquarters: "Nongpoh" },
      { name: "West Jaintia Hills", headquarters: "Jowai" },
      { name: "East Jaintia Hills", headquarters: "Khliehriat" },
      { name: "West Garo Hills", headquarters: "Tura" },
      { name: "East Garo Hills", headquarters: "Williamnagar" },
      { name: "South Garo Hills", headquarters: "Baghmara" },
      { name: "North Garo Hills", headquarters: "Resubelpara" },
      { name: "South West Garo Hills", headquarters: "Ampati" },
    ],
    rssKeywords: ["meghalaya", "shillong"],
  },
  {
    id: "mizoram",
    name: "Mizoram",
    code: "MZ",
    type: "state",
    languages: ["en", "miz"],
    capital: "Aizawl",
    color: "bg-teal-400",
    flagEmoji: "🌸",
    region: "northeast",
    cities: ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib", "Lawngtlai", "Mamit", "Saiha"],
    districts: [
      { name: "Aizawl", headquarters: "Aizawl" },
      { name: "Lunglei", headquarters: "Lunglei" },
      { name: "Champhai", headquarters: "Champhai" },
      { name: "Serchhip", headquarters: "Serchhip" },
      { name: "Kolasib", headquarters: "Kolasib" },
      { name: "Lawngtlai", headquarters: "Lawngtlai" },
      { name: "Mamit", headquarters: "Mamit" },
      { name: "Siaha", headquarters: "Siaha" },
      { name: "Saitual", headquarters: "Saitual" },
      { name: "Khawzawl", headquarters: "Khawzawl" },
      { name: "Hnahthial", headquarters: "Hnahthial" },
    ],
    rssKeywords: ["mizoram", "aizawl", "mizo"],
  },
  {
    id: "nagaland",
    name: "Nagaland",
    code: "NL",
    type: "state",
    languages: ["en"],
    capital: "Kohima",
    color: "bg-teal-300",
    flagEmoji: "🦅",
    region: "northeast",
    cities: ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Zunheboto", "Mon", "Phek"],
    districts: [
      { name: "Kohima", headquarters: "Kohima" },
      { name: "Dimapur", headquarters: "Dimapur" },
      { name: "Mokokchung", headquarters: "Mokokchung" },
      { name: "Tuensang", headquarters: "Tuensang" },
      { name: "Wokha", headquarters: "Wokha" },
      { name: "Zunheboto", headquarters: "Zunheboto" },
      { name: "Mon", headquarters: "Mon" },
      { name: "Phek", headquarters: "Phek" },
      { name: "Longleng", headquarters: "Longleng" },
      { name: "Kiphire", headquarters: "Kiphire" },
      { name: "Peren", headquarters: "Peren" },
      { name: "Chumukedima", headquarters: "Chumukedima" },
      { name: "Niuland", headquarters: "Niuland" },
      { name: "Noklak", headquarters: "Noklak" },
      { name: "Shamator", headquarters: "Shamator" },
      { name: "Tseminyu", headquarters: "Tseminyu" },
    ],
    rssKeywords: ["nagaland", "kohima", "dimapur"],
  },
  {
    id: "tripura",
    name: "Tripura",
    code: "TR",
    type: "state",
    languages: ["bn", "en", "kok"],
    capital: "Agartala",
    color: "bg-green-500",
    flagEmoji: "🎭",
    region: "northeast",
    cities: ["Agartala", "Udaipur", "Dharmanagar", "Kailasahar", "Belonia", "Ambassa", "Khowai", "Teliamura"],
    districts: [
      { name: "West Tripura", headquarters: "Agartala" },
      { name: "South Tripura", headquarters: "Udaipur" },
      { name: "North Tripura", headquarters: "Dharmanagar" },
      { name: "Unakoti", headquarters: "Kailasahar" },
      { name: "Dhalai", headquarters: "Ambassa" },
      { name: "Khowai", headquarters: "Khowai" },
      { name: "Gomati", headquarters: "Udaipur" },
      { name: "Sepahijala", headquarters: "Bishalgarh" },
    ],
    rssKeywords: ["tripura", "agartala", "ত্রিপুরা"],
  },
];

// Union Territories configuration
export const UNION_TERRITORIES_CONFIG: StateConfig[] = [
  {
    id: "delhi",
    name: "Delhi",
    code: "DL",
    type: "ut",
    languages: ["hi", "en"],
    capital: "New Delhi",
    color: "bg-orange-500",
    flagEmoji: "🏛️",
    region: "north",
    cities: ["New Delhi", "Old Delhi", "Dwarka", "Rohini", "Saket", "Connaught Place", "Karol Bagh", "Chandni Chowk"],
    districts: [
      { name: "Central Delhi", headquarters: "Daryaganj" },
      { name: "East Delhi", headquarters: "Gandhi Nagar" },
      { name: "New Delhi", headquarters: "New Delhi" },
      { name: "North Delhi", headquarters: "Civil Lines" },
      { name: "North East Delhi", headquarters: "Seelampur" },
      { name: "North West Delhi", headquarters: "Kanjhawala" },
      { name: "Shahdara", headquarters: "Shahdara" },
      { name: "South Delhi", headquarters: "Hauz Khas" },
      { name: "South East Delhi", headquarters: "Defence Colony" },
      { name: "South West Delhi", headquarters: "Vasant Vihar" },
      { name: "West Delhi", headquarters: "Rajouri Garden" },
    ],
    rssKeywords: ["delhi", "new delhi", "दिल्ली"],
  },
  {
    id: "chandigarh",
    name: "Chandigarh",
    code: "CH",
    type: "ut",
    languages: ["hi", "en", "pa"],
    capital: "Chandigarh",
    color: "bg-amber-600",
    flagEmoji: "🏛️",
    region: "north",
    cities: ["Chandigarh", "Manimajra"],
    districts: [
      { name: "Chandigarh", headquarters: "Chandigarh" },
    ],
    rssKeywords: ["chandigarh", "चंडीगढ़"],
  },
  {
    id: "jammu-kashmir",
    name: "Jammu & Kashmir",
    code: "JK",
    type: "ut",
    languages: ["ur", "hi", "en"],
    capital: "Srinagar",
    color: "bg-rose-400",
    flagEmoji: "🏔️",
    region: "north",
    cities: ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Kupwara", "Sopore", "Kathua", "Udhampur"],
    districts: [
      { name: "Srinagar", headquarters: "Srinagar" },
      { name: "Jammu", headquarters: "Jammu" },
      { name: "Anantnag", headquarters: "Anantnag" },
      { name: "Baramulla", headquarters: "Baramulla" },
      { name: "Kupwara", headquarters: "Kupwara" },
      { name: "Pulwama", headquarters: "Pulwama" },
      { name: "Shopian", headquarters: "Shopian" },
      { name: "Kulgam", headquarters: "Kulgam" },
      { name: "Budgam", headquarters: "Budgam" },
      { name: "Ganderbal", headquarters: "Ganderbal" },
      { name: "Bandipora", headquarters: "Bandipora" },
      { name: "Kathua", headquarters: "Kathua" },
      { name: "Udhampur", headquarters: "Udhampur" },
      { name: "Doda", headquarters: "Doda" },
      { name: "Kishtwar", headquarters: "Kishtwar" },
      { name: "Ramban", headquarters: "Ramban" },
      { name: "Reasi", headquarters: "Reasi" },
      { name: "Samba", headquarters: "Samba" },
      { name: "Poonch", headquarters: "Poonch" },
      { name: "Rajouri", headquarters: "Rajouri" },
    ],
    rssKeywords: ["kashmir", "jammu", "srinagar", "कश्मीर"],
  },
  {
    id: "ladakh",
    name: "Ladakh",
    code: "LA",
    type: "ut",
    languages: ["en", "hi", "bod"],
    capital: "Leh",
    color: "bg-rose-300",
    flagEmoji: "🏔️",
    region: "north",
    cities: ["Leh", "Kargil", "Diskit", "Padum"],
    districts: [
      { name: "Leh", headquarters: "Leh" },
      { name: "Kargil", headquarters: "Kargil" },
    ],
    rssKeywords: ["ladakh", "leh", "kargil", "लद्दाख"],
  },
  {
    id: "puducherry",
    name: "Puducherry",
    code: "PY",
    type: "ut",
    languages: ["ta", "en", "ml", "te"],
    capital: "Puducherry",
    color: "bg-green-500",
    flagEmoji: "🏖️",
    region: "south",
    cities: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
    districts: [
      { name: "Puducherry", headquarters: "Puducherry" },
      { name: "Karaikal", headquarters: "Karaikal" },
      { name: "Mahe", headquarters: "Mahe" },
      { name: "Yanam", headquarters: "Yanam" },
    ],
    rssKeywords: ["puducherry", "pondicherry", "புதுச்சேரி"],
  },
  {
    id: "andaman-nicobar",
    name: "Andaman & Nicobar Islands",
    code: "AN",
    type: "ut",
    languages: ["en", "hi", "bn"],
    capital: "Port Blair",
    color: "bg-blue-500",
    flagEmoji: "🏝️",
    region: "south",
    cities: ["Port Blair", "Car Nicobar", "Campbell Bay", "Diglipur", "Rangat", "Mayabunder"],
    districts: [
      { name: "South Andaman", headquarters: "Port Blair" },
      { name: "North and Middle Andaman", headquarters: "Mayabunder" },
      { name: "Nicobar", headquarters: "Car Nicobar" },
    ],
    rssKeywords: ["andaman", "nicobar", "port blair"],
  },
  {
    id: "lakshadweep",
    name: "Lakshadweep",
    code: "LD",
    type: "ut",
    languages: ["ml", "en"],
    capital: "Kavaratti",
    color: "bg-teal-500",
    flagEmoji: "🏝️",
    region: "south",
    cities: ["Kavaratti", "Agatti", "Minicoy", "Amini", "Andrott", "Kalpeni"],
    districts: [
      { name: "Lakshadweep", headquarters: "Kavaratti" },
    ],
    rssKeywords: ["lakshadweep", "kavaratti", "ലക്ഷദ്വീപ്"],
  },
  {
    id: "dadra-nagar-haveli-daman-diu",
    name: "Dadra & Nagar Haveli and Daman & Diu",
    code: "DN",
    type: "ut",
    languages: ["gu", "hi", "en"],
    capital: "Daman",
    color: "bg-indigo-400",
    flagEmoji: "🌊",
    region: "west",
    cities: ["Daman", "Diu", "Silvassa", "Vapi"],
    districts: [
      { name: "Dadra and Nagar Haveli", headquarters: "Silvassa" },
      { name: "Daman", headquarters: "Daman" },
      { name: "Diu", headquarters: "Diu" },
    ],
    rssKeywords: ["daman", "diu", "silvassa", "dadra"],
  },
];

// Combined configuration
export const ALL_REGIONS_CONFIG: StateConfig[] = [
  ...INDIAN_STATES_CONFIG,
  ...UNION_TERRITORIES_CONFIG,
];

// Helper function to get state config by ID
export function getStateConfig(stateId: string): StateConfig | undefined {
  return ALL_REGIONS_CONFIG.find(s => s.id === stateId.toLowerCase());
}

// Helper function to get language config
export function getLanguageConfig(langCode: string) {
  return LANGUAGE_CONFIG[langCode];
}

// Helper function to get flag info
export function getStateFlag(stateId: string) {
  return STATE_FLAGS[stateId.toLowerCase()];
}

// Region groupings
export const REGION_GROUPS = {
  north: ["delhi", "uttar-pradesh", "uttarakhand", "haryana", "punjab", "himachal-pradesh", "jammu-kashmir", "ladakh", "chandigarh"],
  south: ["karnataka", "kerala", "tamil-nadu", "andhra-pradesh", "telangana", "puducherry", "andaman-nicobar", "lakshadweep"],
  east: ["west-bengal", "bihar", "jharkhand", "odisha"],
  west: ["rajasthan", "gujarat", "maharashtra", "goa", "dadra-nagar-haveli-daman-diu"],
  central: ["madhya-pradesh", "chhattisgarh"],
  northeast: ["assam", "arunachal-pradesh", "manipur", "meghalaya", "mizoram", "nagaland", "tripura", "sikkim"],
};
